openapi: 3.0.0
info:
  title: Transfers
  description: Contrato para MS
  version: 1.3.00
servers:
- url: /v1/transfers

security:
  - bearerAuth: []

tags:
  - name: Transfers
    description: Informacion sobre el API transfers 
    externalDocs:
      description: Find out more
      url: https://TBD #poner url correcta
paths:
#--------------------------------------------------------------------
# GET - Consulta de agenda de transferencias
#-------------------------------------------------------------------- 
  /customers-document/{customer-document-number}/recipients:
    get:
      tags:
        - Transfers
      summary: Agenda de destinatarios de transferencias de un cliente
      description: Con este servicio se informarar la agenda de transferencias de un cliente
      operationId: get-recipients
      parameters:
        - name: customer-document-number
          in: path
          required: true
          schema:
            type: string
            pattern: '^\d+$'
          examples: 
            200: 
              value: "32345379"
            404: 
              value: "32345380" 
          description: Numero de documento del cliente
        - name: customer-document-type
          in: query
          required: true
          schema:
            type: string
            enum:
              - "01" #DNI 
              - "02" #LE  
              - "03" #LC  
              - "11" # CUIT
              - "101" #CI 
              - "125" #PAS
            example: "01"
          description: Tipo de documento del cliente
                
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              examples:
                none:
                  summary: ""
                200-OK: 
                  $ref: '#/components/examples/recipients-200-response'
              schema:
                $ref: '#/components/schemas/recipients-get-response' #Idem anterior, sería mas específico en su nombre #OK
        '400':
          $ref: '#/components/responses/badRequest'
        '401': 
          $ref: '#/components/responses/unauthorized'
        '404': 
          $ref: '#/components/responses/notFound'
        '409':
          $ref: '#/components/responses/conflict'
        '429': 
          $ref: '#/components/responses/tooManyRequests'
        '500': 
          $ref: '#/components/responses/internalServerError'
        '502': 
          $ref: '#/components/responses/BadGateway'
        '503':
          $ref: '#/components/responses/serviceUnavailable'
        '504':
          $ref: '#/components/responses/GatewayTimeout'
       
components:
  schemas:
  #-------------------------------------------------------------------
  # GET - response - Consulta de agenda de transferencias
  #-------------------------------------------------------------------
    recipients-get-response:
      type: object
      properties:
        recipient:
          type: array
          description: Lista de destinatarios agendados
          items:
            $ref: '#/components/schemas/recipients-get-response-data'

    recipients-get-response-data:
      type: object
      properties:
        cuit:
          type: string
          pattern: '^(20|23|24|25|26|27|30|33|34)[0-9]{9}$'
          example: ""
          description: Numero de cuit del destinatario
        description:
          type: string
          example: ""
          description: Descripcion del destinatario
        account:
          type: object
          properties:
            cbu:
              type: string
              maxLength: 22
              pattern: '^\d+$'
              example: ""
              description: CBU de la cuenta del destinatario
            code: 
              type: integer
              enum:
                - 1 #Es una cuenta corriente propia
                - 2 #Es una cuenta corriente no propia
                - 3 #Es otra cuenta propia
                - 4 #Es otra cuenta no propia
              example: 3
              description: Tipo de cuenta del destinatario
            description: 
              type: string
              example: ""
              description: Descripcion de la cuenta del destinatario
            current: 
              type: boolean
              example: false
              description: Indica si es cuenta corriente o no
            own: 
              type: boolean
              example: true
              description: Indica si es una cuenta propia o no
       
  #------------------------------------------------------------------
  # ERROR
  #-------------------------------------------------------------------
    error: 
      type: object
      properties:
        Code:
          type: string
          example: "ERR-XXX"
        Id:
          type: string
          example: "81cfc331-5726-42c6-8a95-2700b45ff5d538919"
        Message:
          type: string
          example: "Error message"
        Errors:
          type: array
          items:
            $ref: '#/components/schemas/errors'
    
    errors:
      type: object
      properties:
        ErrorCode:
          type: string
          example: "ER-XXX"
        Message:
          type: string
          example: "Error message"
        Path:
          type: string
          example: "/customers-document/32345380/recipients.."
  

  #-----------------------------------------------------------------
 
  responses:
    badRequest:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    unauthorized: 
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    notFound: 
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    conflict: 
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    tooManyRequests:
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    internalServerError: 
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    BadGateway:
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    serviceUnavailable: 
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    GatewayTimeout: 
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  
  #-------------------------------------------------------------------
  # Ejemplos
  #-------------------------------------------------------------------
  examples: 
    recipients-200-response:
      value:
        recipients:  
          - 
            cuit: "27283221145"
            description: "ROSA LOPEZ"
            account: 
                cbu: "2850672840027388702207"
                code: 4
                description: "Es Otra Cuenta No Propia"
                current: true
                own: false
          - 
            cuit: "20172997989"
            description: "FONTANA AMILCAR DANIEL"
            account: 
                cbu: "2850001040094059465088"
                code: 3
                description: " Es otra cuenta propia"
                current: false
                own: true           
